# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/raymondtay/GPUMLib

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/raymondtay/GPUMLib

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CMake.app/Contents/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CMake.app/Contents/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/raymondtay/GPUMLib/CMakeFiles /Users/raymondtay/GPUMLib/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/raymondtay/GPUMLib/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GPUMLibDBN

# Build rule for target.
GPUMLibDBN: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GPUMLibDBN
.PHONY : GPUMLibDBN

# fast build rule for target.
GPUMLibDBN/fast:
	$(MAKE) -f src/CMakeFiles/GPUMLibDBN.dir/build.make src/CMakeFiles/GPUMLibDBN.dir/build
.PHONY : GPUMLibDBN/fast

#=============================================================================
# Target rules for targets named GPUMLibMBP

# Build rule for target.
GPUMLibMBP: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GPUMLibMBP
.PHONY : GPUMLibMBP

# fast build rule for target.
GPUMLibMBP/fast:
	$(MAKE) -f src/CMakeFiles/GPUMLibMBP.dir/build.make src/CMakeFiles/GPUMLibMBP.dir/build
.PHONY : GPUMLibMBP/fast

#=============================================================================
# Target rules for targets named GPUMLibNMF

# Build rule for target.
GPUMLibNMF: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GPUMLibNMF
.PHONY : GPUMLibNMF

# fast build rule for target.
GPUMLibNMF/fast:
	$(MAKE) -f src/CMakeFiles/GPUMLibNMF.dir/build.make src/CMakeFiles/GPUMLibNMF.dir/build
.PHONY : GPUMLibNMF/fast

#=============================================================================
# Target rules for targets named GPUMLibRAN

# Build rule for target.
GPUMLibRAN: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GPUMLibRAN
.PHONY : GPUMLibRAN

# fast build rule for target.
GPUMLibRAN/fast:
	$(MAKE) -f src/CMakeFiles/GPUMLibRAN.dir/build.make src/CMakeFiles/GPUMLibRAN.dir/build
.PHONY : GPUMLibRAN/fast

#=============================================================================
# Target rules for targets named GPUMLibRBF

# Build rule for target.
GPUMLibRBF: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GPUMLibRBF
.PHONY : GPUMLibRBF

# fast build rule for target.
GPUMLibRBF/fast:
	$(MAKE) -f src/CMakeFiles/GPUMLibRBF.dir/build.make src/CMakeFiles/GPUMLibRBF.dir/build
.PHONY : GPUMLibRBF/fast

#=============================================================================
# Target rules for targets named GPUMLibUtils

# Build rule for target.
GPUMLibUtils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GPUMLibUtils
.PHONY : GPUMLibUtils

# fast build rule for target.
GPUMLibUtils/fast:
	$(MAKE) -f src/CMakeFiles/GPUMLibUtils.dir/build.make src/CMakeFiles/GPUMLibUtils.dir/build
.PHONY : GPUMLibUtils/fast

#=============================================================================
# Target rules for targets named ATS

# Build rule for target.
ATS: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ATS
.PHONY : ATS

# fast build rule for target.
ATS/fast:
	$(MAKE) -f src/examples/ATS/CMakeFiles/ATS.dir/build.make src/examples/ATS/CMakeFiles/ATS.dir/build
.PHONY : ATS/fast

#=============================================================================
# Target rules for targets named BP

# Build rule for target.
BP: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BP
.PHONY : BP

# fast build rule for target.
BP/fast:
	$(MAKE) -f src/examples/BP/CMakeFiles/BP.dir/build.make src/examples/BP/CMakeFiles/BP.dir/build
.PHONY : BP/fast

#=============================================================================
# Target rules for targets named MBP

# Build rule for target.
MBP: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MBP
.PHONY : MBP

# fast build rule for target.
MBP/fast:
	$(MAKE) -f src/examples/MBP/CMakeFiles/MBP.dir/build.make src/examples/MBP/CMakeFiles/MBP.dir/build
.PHONY : MBP/fast

#=============================================================================
# Target rules for targets named RAN

# Build rule for target.
RAN: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RAN
.PHONY : RAN

# fast build rule for target.
RAN/fast:
	$(MAKE) -f src/examples/RAN/CMakeFiles/RAN.dir/build.make src/examples/RAN/CMakeFiles/RAN.dir/build
.PHONY : RAN/fast

#=============================================================================
# Target rules for targets named RBF

# Build rule for target.
RBF: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RBF
.PHONY : RBF

# fast build rule for target.
RBF/fast:
	$(MAKE) -f src/examples/RBF/CMakeFiles/RBF.dir/build.make src/examples/RBF/CMakeFiles/RBF.dir/build
.PHONY : RBF/fast

#=============================================================================
# Target rules for targets named DBN

# Build rule for target.
DBN: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DBN
.PHONY : DBN

# fast build rule for target.
DBN/fast:
	$(MAKE) -f src/examples/DBN/CMakeFiles/DBN.dir/build.make src/examples/DBN/CMakeFiles/DBN.dir/build
.PHONY : DBN/fast

#=============================================================================
# Target rules for targets named reductionapp

# Build rule for target.
reductionapp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 reductionapp
.PHONY : reductionapp

# fast build rule for target.
reductionapp/fast:
	$(MAKE) -f src/examples/reduction/CMakeFiles/reductionapp.dir/build.make src/examples/reduction/CMakeFiles/reductionapp.dir/build
.PHONY : reductionapp/fast

#=============================================================================
# Target rules for targets named svm

# Build rule for target.
svm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 svm
.PHONY : svm

# fast build rule for target.
svm/fast:
	$(MAKE) -f src/examples/SVM/CMakeFiles/svm.dir/build.make src/examples/SVM/CMakeFiles/svm.dir/build
.PHONY : svm/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... GPUMLibRBF"
	@echo "... GPUMLibRAN"
	@echo "... GPUMLibDBN"
	@echo "... GPUMLibUtils"
	@echo "... GPUMLibMBP"
	@echo "... GPUMLibNMF"
	@echo "... ATS"
	@echo "... BP"
	@echo "... MBP"
	@echo "... RAN"
	@echo "... RBF"
	@echo "... DBN"
	@echo "... reductionapp"
	@echo "... svm"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

